name: Build Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd Project/EnchantReaderDesktop
          npm install --no-audit --no-fund

      - name: Build installer
        run: |
          cd Project/EnchantReaderDesktop
          npx electron-builder --win --x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EnchantReader-Desktop-Installer
          path: Project/EnchantReaderDesktop/dist/*
